parameters:
  Artifacts: []
  ServiceDirectory: not-specified

jobs:
  - job: GenerateDocs
    pool:
      vmImage: windows-2019
    steps:
      - pwsh: >-
          choco install doxygen.install
        displayName: Install Doxygen

      - ${{ each artifact in parameters.Artifacts }}:
        - pwsh: Write-Host "##vso[task.setvariable variable=PackageVersion]$(Get-Content .\sdk\${{ parameters.ServiceDirectory }}\${{ artifact.Path }}\version.txt)"
          displayName: Set $(PackageVersion) from version.txt file
        - pwsh: >-
            python eng/docs/api/generate_docs.py
            --TemplateFile="eng/docs/api/Doxyfile.template"
            --PackagePath="sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}"
            --PackageName="${{ artifact.Name }}"
            --PackageVersion="$(PackageVersion)"
            --AssetsPath="eng/docs/api/assets"
            --DoxygenPath="c:\\program files\\doxygen\\bin\\doxygen.exe"
          displayName: Fill in Doxyfile.template

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/html
            artifactName: docs
            path: $(Build.ArtifactStagingDirectory)/docs/${{ artifact.Name }}