resources:
  repositories:
      # Update refs to get to newer versions of build tools. Make sure to update
      # refs in all relevant files to apply the changes universally.
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      # ref: a2b377867a889f1417089023b6f94f28e324b180
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
      # ref: 7056936fa8315e18852759e4a1a9041dbfeeea3a
      ref: djurek/c-release

trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: core
      Artifacts:
        - Name: az_core
          Path: core